name: Main

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16.14.2

jobs:
  cypress:
    name: Cypress CI-CD Execution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}   

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          always-auth: true
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - uses: cypress-io/github-action@v4
        with:
          command: npm run cypress:run
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{ secrets.AWS_REGION}}
          
      - name: Upload cypress report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-report
          path: cypress/report/index.html